#!/bin/bash

# Define the IP addresses of the AWS servers
server_ips=("52.3.249.117" "18.214.87.145" "100.24.74.154")

# Loop through each server IP and SSH into it
for ip in "${server_ips[@]}"; do
    gnome-terminal --tab --title="SSH $ip" -- bash -c "ssh -i ~/.ssh/schoolubuntu@$ip; exec bash"
    
done